const { Product } = require("../models");

const productData = [
  {
    product_name: "Cheese",
    price: 2.69,
    department_id: 2,
    aisle_id: 1,
  },
  {
    product_name: "Yogurt",
    price: 3.69,
    department_id: 2,
    aisle_id: 1,
  },
  {
    product_name: "Sour Cream",
    price: 2.49,
    department_id: 2,
    aisle_id: 1,
  },
  {
    product_name: "Orange Juice",
    price: 2.39,
    department_id: 2,
    aisle_id: 1,
  },
  {
    product_name: "Milk",
    price: 1.49,
    department_id: 2,
    aisle_id: 1,
  },
  {
    product_name: "Eggs",
    price: 1.69,
    department_id: 2,
    aisle_id: 1,
  },
  {
    product_name: "Cottage Cheese",
    price: 2.39,
    department_id: 2,
    aisle_id: 1,
  },
  {
    product_name: "Bacon",
    price: 3.79,
    department_id: 5,
    aisle_id: 1,
  },
  {
    product_name: "Hot Dogs",
    price: 3.79,
    department_id: 5,
    aisle_id: 1,
  },
  {
    product_name: "Ketchup",
    price: 3.69,
    department_id: 1,
    aisle_id: 2,
  },
  {
    product_name: "Pickles",
    price: 2.99,
    department_id: 1,
    aisle_id: 2,
  },
  {
    product_name: "Barbeque Sauce",
    price: 3.49,
    department_id: 1,
    aisle_id: 2,
  },
  {
    product_name: "Vinegar",
    price: 2.79,
    department_id: 1,
    aisle_id: 2,
  },
  {
    product_name: "Salad Dressing",
    price: 3.99,
    department_id: 1,
    aisle_id: 2,
  },
  {
    product_name: "Tuna",
    price: 1.69,
    department_id: 1,
    aisle_id: 2,
  },
  {
    product_name: "Taco Shells",
    price: 2.59,
    department_id: 1,
    aisle_id: 2,
  },
  {
    product_name: "Salsa",
    price: 2.49,
    department_id: 1,
    aisle_id: 2,
  },
  {
    product_name: "Cereal",
    price: 3.99,
    department_id: 1,
    aisle_id: 3,
  },
  {
    product_name: "Rice Krispy Treats",
    price: 2.59,
    department_id: 1,
    aisle_id: 3,
  },
  {
    product_name: "Granola Bars",
    price: 2.99,
    department_id: 1,
    aisle_id: 3,
  },
  {
    product_name: "Pop Tarts",
    price: 1.59,
    department_id: 1,
    aisle_id: 3,
  },
  {
    product_name: "Rice Cakes",
    price: 2.99,
    department_id: 1,
    aisle_id: 3,
  },
  {
    product_name: "Oatmeal",
    price: 2.59,
    department_id: 1,
    aisle_id: 3,
  },
  {
    product_name: "Grits",
    price: 2.19,
    department_id: 1,
    aisle_id: 3,
  },
  {
    product_name: "Wheat Germ",
    price: 3.99,
    department_id: 1,
    aisle_id: 3,
  },
  {
    product_name: "Rice",
    price: 2.99,
    department_id: 1,
    aisle_id: 4,
  },
  {
    product_name: "Pasta",
    price: 1.99,
    department_id: 1,
    aisle_id: 4,
  },
  {
    product_name: "Pasta Sauce",
    price: 2.59,
    department_id: 1,
    aisle_id: 4,
  },
  {
    product_name: "Dinty Moore Beef Stew",
    price: 3.69,
    department_id: 1,
    aisle_id: 4,
  },
  {
    product_name: "Canned Tomatoes",
    price: 2.39,
    department_id: 1,
    aisle_id: 4,
  },
  {
    product_name: "Macaroni and Cheese",
    price: 1.99,
    department_id: 1,
    aisle_id: 4,
  },
  {
    product_name: "Hamburger Helper",
    price: 1.39,
    department_id: 1,
    aisle_id: 4,
  },
  {
    product_name: "Quinoa",
    price: 4.69,
    department_id: 1,
    aisle_id: 4,
  },
  {
    product_name: "Gatorade",
    price: 1.49,
    department_id: 1,
    aisle_id: 5,
  },
  {
    product_name: "Juice Boxes",
    price: 2.39,
    department_id: 1,
    aisle_id: 5,
  },
  {
    product_name: "Lemon Juice",
    price: 2.69,
    department_id: 1,
    aisle_id: 5,
  },
  {
    product_name: "French Fried Onions",
    price: 2.5,
    department_id: 1,
    aisle_id: 5,
  },
  {
    product_name: "Sauerkraut",
    price: 1.69,
    department_id: 1,
    aisle_id: 5,
  },
  {
    product_name: "Instant Potatoes",
    price: 0.99,
    department_id: 1,
    aisle_id: 5,
  },
  {
    product_name: "Canned Mushrooms",
    price: 1.49,
    department_id: 1,
    aisle_id: 5,
  },
  {
    product_name: "Dried Beans",
    price: 2.69,
    department_id: 1,
    aisle_id: 5,
  },
  {
    product_name: "Flour",
    price: 2.49,
    department_id: 1,
    aisle_id: 6,
  },
  {
    product_name: "Sugar",
    price: 1.69,
    department_id: 1,
    aisle_id: 6,
  },
  {
    product_name: "Coffee",
    price: 5.69,
    department_id: 1,
    aisle_id: 6,
  },
  {
    product_name: "Tea",
    price: 4.69,
    department_id: 1,
    aisle_id: 6,
  },
  {
    product_name: "Hot Chocolate",
    price: 1.59,
    department_id: 1,
    aisle_id: 6,
  },
  {
    product_name: "Cake Mix",
    price: 2.49,
    department_id: 1,
    aisle_id: 6,
  },
  {
    product_name: "Cookie Mix",
    price: 2.49,
    department_id: 1,
    aisle_id: 6,
  },
  {
    product_name: "Jello",
    price: 0.99,
    department_id: 1,
    aisle_id: 6,
  },
  {
    product_name: "Crackers",
    price: 2.29,
    department_id: 1,
    aisle_id: 7,
  },
  {
    product_name: "Applesauce",
    price: 2.49,
    department_id: 1,
    aisle_id: 7,
  },
  {
    product_name: "Pancake Mix",
    price: 1.39,
    department_id: 1,
    aisle_id: 7,
  },
  {
    product_name: "Honey",
    price: 3.49,
    department_id: 1,
    aisle_id: 7,
  },
  {
    product_name: "Syrup",
    price: 2.39,
    department_id: 1,
    aisle_id: 7,
  },
  {
    product_name: "Peanut Butter",
    price: 2.29,
    department_id: 1,
    aisle_id: 7,
  },
  {
    product_name: "Candy",
    price: 3.69,
    department_id: 1,
    aisle_id: 7,
  },
  {
    product_name: "Jelly",
    price: 2.49,
    department_id: 1,
    aisle_id: 7,
  },
  {
    product_name: "Soup",
    price: 1.69,
    department_id: 1,
    aisle_id: 8,
  },
  {
    product_name: "Fruit Snacks",
    price: 2.49,
    department_id: 1,
    aisle_id: 8,
  },
  {
    product_name: "Broth",
    price: 2.69,
    department_id: 1,
    aisle_id: 8,
  },
  {
    product_name: "Ramen Noodles",
    price: 0.99,
    department_id: 1,
    aisle_id: 8,
  },
  {
    product_name: "Pepperoncini",
    price: 2.99,
    department_id: 1,
    aisle_id: 8,
  },
  {
    product_name: "Popcorn",
    price: 1.59,
    department_id: 1,
    aisle_id: 8,
  },
  {
    product_name: "Dried Fruit",
    price: 2.99,
    department_id: 1,
    aisle_id: 8,
  },
  {
    product_name: "Goya",
    price: 2.99,
    department_id: 1,
    aisle_id: 8,
  },
  {
    product_name: "Diapers",
    price: 12.99,
    department_id: 1,
    aisle_id: 9,
  },
  {
    product_name: "Baby Food",
    price: 2.99,
    department_id: 1,
    aisle_id: 9,
  },
  {
    product_name: "Wrapping Paper",
    price: 1.99,
    department_id: 1,
    aisle_id: 9,
  },
  {
    product_name: "Condoms",
    price: 3.99,
    department_id: 1,
    aisle_id: 9,
  },
  {
    product_name: "Socks",
    price: 2.99,
    department_id: 1,
    aisle_id: 9,
  },
  {
    product_name: "Pedialyte",
    price: 3.79,
    department_id: 1,
    aisle_id: 9,
  },
  {
    product_name: "Office Supplies",
    price: 2.99,
    department_id: 1,
    aisle_id: 9,
  },
  {
    product_name: "Baby Wipes",
    price: 2.99,
    department_id: 1,
    aisle_id: 9,
  },
  {
    product_name: "Shampoo",
    price: 4.99,
    department_id: 1,
    aisle_id: 10,
  },
  {
    product_name: "Conditioner",
    price: 4.99,
    department_id: 1,
    aisle_id: 10,
  },
  {
    product_name: "Hairspray",
    price: 3.99,
    department_id: 1,
    aisle_id: 10,
  },
  {
    product_name: "Deodorant",
    price: 2.69,
    department_id: 1,
    aisle_id: 10,
  },
  {
    product_name: "Mouthwash",
    price: 1.99,
    department_id: 1,
    aisle_id: 20,
  },
  {
    product_name: "Toothpaste",
    price: 2.99,
    department_id: 1,
    aisle_id: 10,
  },
  {
    product_name: "Vitamins",
    price: 6.99,
    department_id: 1,
    aisle_id: 10,
  },
  {
    product_name: "Protein Drinks",
    price: 3.99,
    department_id: 1,
    aisle_id: 10,
  },
  {
    product_name: "Body Wash",
    price: 4.99,
    department_id: 1,
    aisle_id: 11,
  },
  {
    product_name: "Hand Sanitizer",
    price: 1.99,
    department_id: 1,
    aisle_id: 11,
  },
  {
    product_name: "Lotion",
    price: 3.99,
    department_id: 1,
    aisle_id: 11,
  },
  {
    product_name: "Hand Soap",
    price: 2.99,
    department_id: 1,
    aisle_id: 11,
  },
  {
    product_name: "Toilet Paper",
    price: 5.99,
    department_id: 1,
    aisle_id: 11,
  },
  {
    product_name: "Tissues",
    price: 2.99,
    department_id: 1,
    aisle_id: 11,
  },
  {
    product_name: "Bandaids",
    price: 1.99,
    department_id: 1,
    aisle_id: 11,
  },
  {
    product_name: "Medicine",
    price: 6.49,
    department_id: 1,
    aisle_id: 11,
  },
  {
    product_name: "Sandwich Bags",
    price: 3.99,
    department_id: 1,
    aisle_id: 12,
  },
  {
    product_name: "Snack Bags",
    price: 2.99,
    department_id: 1,
    aisle_id: 12,
  },
  {
    product_name: "Wax Paper",
    price: 2.49,
    department_id: 1,
    aisle_id: 12,
  },
  {
    product_name: "Aluminum Foil",
    price: 4.99,
    department_id: 1,
    aisle_id: 12,
  },
  {
    product_name: "Paper Plates",
    price: 3.39,
    department_id: 1,
    aisle_id: 12,
  },
  {
    product_name: "Napkins",
    price: 3.99,
    department_id: 1,
    aisle_id: 12,
  },
  {
    product_name: "Paper Towels",
    price: 12.99,
    department_id: 1,
    aisle_id: 12,
  },
  {
    product_name: "Toothpicks",
    price: 0.99,
    department_id: 1,
    aisle_id: 12,
  },
  {
    product_name: "Cat Food",
    price: 7.99,
    department_id: 1,
    aisle_id: 13,
  },
  {
    product_name: "Dog Food",
    price: 8.99,
    department_id: 1,
    aisle_id: 13,
  },
  {
    product_name: "Dog Treats",
    price: 4.99,
    department_id: 1,
    aisle_id: 13,
  },
  {
    product_name: "Cat Treats",
    price: 3.99,
    department_id: 1,
    aisle_id: 13,
  },
  {
    product_name: "Cat Litter",
    price: 9.99,
    department_id: 1,
    aisle_id: 13,
  },
  {
    product_name: "Dog Toys",
    price: 3.99,
    department_id: 1,
    aisle_id: 13,
  },
  {
    product_name: "Cat Toys",
    price: 2.99,
    department_id: 1,
    aisle_id: 13,
  },
  {
    product_name: "Bird Food",
    price: 7.99,
    department_id: 1,
    aisle_id: 13,
  },
  {
    product_name: "Dish Soap",
    price: 3.99,
    department_id: 1,
    aisle_id: 14,
  },
  {
    product_name: "Bleach",
    price: 7.99,
    department_id: 1,
    aisle_id: 14,
  },
  {
    product_name: "Ammonia",
    price: 6.99,
    department_id: 1,
    aisle_id: 14,
  },
  {
    product_name: "Sponges",
    price: 1.99,
    department_id: 1,
    aisle_id: 14,
  },
  {
    product_name: "Lysol",
    price: 3.99,
    department_id: 1,
    aisle_id: 14,
  },
  {
    product_name: "Laundry Detergent",
    price: 8.99,
    department_id: 1,
    aisle_id: 8,
  },
  {
    product_name: "Candles",
    price: 1.99,
    department_id: 1,
    aisle_id: 14,
  },
  {
    product_name: "Cleaning Supplies",
    price: 5.99,
    department_id: 1,
    aisle_id: 14,
  },
  {
    product_name: "Laundry Sheets",
    price: 2.99,
    department_id: 1,
    aisle_id: 14,
  },
  {
    product_name: "Case Water",
    price: 1.99,
    department_id: 1,
    aisle_id: 15,
  },
  {
    product_name: "Propel",
    price: 4.99,
    department_id: 1,
    aisle_id: 15,
  },
  {
    product_name: "Flavored Water",
    price: 2.99,
    department_id: 1,
    aisle_id: 15,
  },
  {
    product_name: "Gallon Water",
    price: 0.99,
    department_id: 1,
    aisle_id: 15,
  },
  {
    product_name: "Seltzer",
    price: 2.99,
    department_id: 1,
    aisle_id: 15,
  },
  {
    product_name: "Water Drink Mix",
    price: 1.39,
    department_id: 1,
    aisle_id: 15,
  },
  {
    product_name: "Powedered Tea Mix",
    price: 2.99,
    department_id: 1,
    aisle_id: 15,
  },
  {
    product_name: "Ice Pops",
    price: 2.99,
    department_id: 1,
    aisle_id: 15,
  },
  {
    product_name: "Coke",
    price: 2.99,
    department_id: 1,
    aisle_id: 16,
  },
  {
    product_name: "Pepsi",
    price: 2.99,
    department_id: 1,
    aisle_id: 16,
  },
  {
    product_name: "Arizona Ice Tea",
    price: 3.99,
    department_id: 1,
    aisle_id: 16,
  },
  {
    product_name: "Energy Drinks",
    price: 3.99,
    department_id: 1,
    aisle_id: 16,
  },
  {
    product_name: "Tonic Water",
    price: 1.99,
    department_id: 1,
    aisle_id: 16,
  },
  {
    product_name: "Club Soda",
    price: 1.39,
    department_id: 1,
    aisle_id: 16,
  },
  {
    product_name: "Snapple Tea",
    price: 3.99,
    department_id: 1,
    aisle_id: 16,
  },
  {
    product_name: "Lipton Tea",
    price: 3.99,
    department_id: 1,
    aisle_id: 16,
  },
  {
    product_name: "Chips",
    price: 2.99,
    department_id: 1,
    aisle_id: 17,
  },
  {
    product_name: "Pretzels",
    price: 1.99,
    department_id: 1,
    aisle_id: 17,
  },
  {
    product_name: "Beef Jerky",
    price: 3.59,
    department_id: 1,
    aisle_id: 17,
  },
  {
    product_name: "Slim Jims",
    price: 1.99,
    department_id: 1,
    aisle_id: 17,
  },
  {
    product_name: "Peanut Butter Crackers",
    price: 3.99,
    department_id: 1,
    aisle_id: 17,
  },
  {
    product_name: "To-Go Snacks",
    price: 0.99,
    department_id: 1,
    aisle_id: 17,
  },
  {
    product_name: "Pringles",
    price: 1.39,
    department_id: 1,
    aisle_id: 17,
  },
  {
    product_name: "Smartfood",
    price: 1.99,
    department_id: 1,
    aisle_id: 17,
  },
  {
    product_name: "Beer",
    price: 4.99,
    department_id: 1,
    aisle_id: 18,
  },
  {
    product_name: "Wine",
    price: 12.99,
    department_id: 1,
    aisle_id: 18,
  },
  {
    product_name: "Champagne",
    price: 9.99,
    department_id: 1,
    aisle_id: 18,
  },
  {
    product_name: "Frozen Sausage",
    price: 4.99,
    department_id: 5,
    aisle_id: 19,
  },
  {
    product_name: "Frozen Hamburgers",
    price: 6.99,
    department_id: 5,
    aisle_id: 19,
  },
  {
    product_name: "Vegetarian Chicken",
    price: 5.99,
    department_id: 5,
    aisle_id: 19,
  },
  {
    product_name: "Vegetarian Beef",
    price: 7.99,
    department_id: 5,
    aisle_id: 19,
  },
  {
    product_name: "Vegetarian Meatballs",
    price: 4.99,
    department_id: 5,
    aisle_id: 19,
  },
  {
    product_name: "Frozen Pizza",
    price: 7.99,
    department_id: 3,
    aisle_id: 19,
  },
  {
    product_name: "Frozen Fruit",
    price: 4.99,
    department_id: 3,
    aisle_id: 19,
  },
  {
    product_name: "Frozen Cake",
    price: 3.79,
    department_id: 3,
    aisle_id: 19,
  },
  {
    product_name: "Frozen Breakfast Sandwich",
    price: 3.99,
    department_id: 3,
    aisle_id: 19,
  },
  {
    product_name: "Frozen Breakfast Bowl",
    price: 3.99,
    department_id: 3,
    aisle_id: 19,
  },
  {
    product_name: "Frozen Bagels",
    price: 2.79,
    department_id: 3,
    aisle_id: 19,
  },
  {
    product_name: "Frozen Juice",
    price: 1.99,
    department_id: 3,
    aisle_id: 19,
  },
  {
    product_name: "Frozen Pie",
    price: 3.99,
    department_id: 3,
    aisle_id: 19,
  },
  {
    product_name: "Frozen French Fries",
    price: 2.39,
    department_id: 3,
    aisle_id: 20,
  },
  {
    product_name: "Frozen Onion Rings",
    price: 3.39,
    department_id: 3,
    aisle_id: 20,
  },
  {
    product_name: "Frozen Vegetables",
    price: 2.99,
    department_id: 3,
    aisle_id: 20,
  },
  {
    product_name: "Frozen Dinner",
    price: 4.39,
    department_id: 3,
    aisle_id: 20,
  },
  {
    product_name: "Gluten Free Frozen Bread",
    price: 3.99,
    department_id: 3,
    aisle_id: 20,
  },
  {
    product_name: "Gluten Free Frozen Bagels",
    price: 2.99,
    department_id: 3,
    aisle_id: 20,
  },
  {
    product_name: "Gluten Free Frozen Cupcakes",
    price: 3.59,
    department_id: 3,
    aisle_id: 20,
  },
  {
    product_name: "Frozen Fish Sticks",
    price: 3.79,
    department_id: 3,
    aisle_id: 20,
  },
  {
    product_name: "Bread",
    price: 2.99,
    department_id: 1,
    aisle_id: 21,
  },
  {
    product_name: "English Muffins",
    price: 3.99,
    department_id: 1,
    aisle_id: 21,
  },
  {
    product_name: "Hot Dog Rolls",
    price: 2.79,
    department_id: 1,
    aisle_id: 21,
  },
  {
    product_name: "Hamburger Buns",
    price: 3.99,
    department_id: 1,
    aisle_id: 21,
  },
  {
    product_name: "Donuts",
    price: 3.59,
    department_id: 1,
    aisle_id: 21,
  },
  {
    product_name: "Bananas",
    price: 3.99,
    department_id: 4,
    aisle_id: 21,
  },
  {
    product_name: "Watermelon",
    price: 3.99,
    department_id: 4,
    aisle_id: 21,
  },
  {
    product_name: "Apples",
    price: 4.99,
    department_id: 4,
    aisle_id: 21,
  },
  {
    product_name: "Broccoli",
    price: 3.99,
    department_id: 4,
    aisle_id: 8,
  },
  {
    product_name: "Carrots",
    price: 2.59,
    department_id: 4,
    aisle_id: 21,
  },
  {
    product_name: "Cucumber",
    price: 1.39,
    department_id: 4,
    aisle_id: 21,
  },
  {
    product_name: "Asparagus",
    price: 1.39,
    department_id: 4,
    aisle_id: 21,
  },
  {
    product_name: "Brussel Sprouts",
    price: 1.49,
    department_id: 4,
    aisle_id: 21,
  },
  {
    product_name: "Ice Cream",
    price: 3.99,
    department_id: 3,
    aisle_id: 21,
  },
  {
    product_name: "Frozen Novelties",
    price: 4.99,
    department_id: 3,
    aisle_id: 21,
  },
];

const seedProduct = () => Product.bulkCreate(productData);

module.exports = seedProduct;
